version: '3.1'

services:
  springboot:
    build: .
    # image: registry.gitlab.com/idgst/springboot-mongo-demo:latest
    restart: always
    container_name: gradle_docker_app
    ports:
      - 9000:9000
      - 9001:9001
    working_dir: /opt/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: gradle_docker-mongo
    url: mongodb://gradle_docker-mongo/rest_tutorial
#    ports:  # for demo/debug purpose only
#      - 27017:27017
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always